apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  # ESTO ES EN BASE64 string  EstoEsElSecretSeedK8s = cmVuaWVyMTk4OUBnbWFpbC5jb20= 
  # JWT_SECRET: RXN0b0VzRWxTZWNyZXRTZWVkSzhz
  # ESTO ES EN BASE64 string  EstoEsElSecretSeedK8sActualizado = RXN0b0VzRWxTZWNyZXRTZWVkSzhzQWN0dWFsaXphZG8= 
  JWT_SECRET: RXN0b0VzRWxTZWNyZXRTZWVkSzhzQWN0dWFsaXphZG8=
