apiVersion: v1
kind: Secret
metadata:
  name: pg-admin-secrets
type: Opaque
data:
  # ESTO ES EN BASE64 string  renier1989@gmail.com = cmVuaWVyMTk4OUBnbWFpbC5jb20= 
  PG_USER_EMAIL: cmVuaWVyMTk4OUBnbWFpbC5jb20=
  # ESTO ES EN BASE64  MYCLAVESECRETA = TVlDTEFWRVNFQ1JFVEE= 
  DB_PASSWORD: TVlDTEFWRVNFQ1JFVEE=