apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  # ESTO ES EN BASE64  postgres = cG9zdGdyZXM= 
  DB_USER: cG9zdGdyZXM=
  # ESTO ES EN BASE64  MYCLAVESECRETA = TVlDTEFWRVNFQ1JFVEE= 
  DB_PASSWORD: TVlDTEFWRVNFQ1JFVEE=